// mdl.h - PulseMDL
//
// On-disk .mdl (studio model, version 49) structures, re-declared from format
// facts (SDK-2013 / CS:GO-era studio.h studied as reference; typed fresh, not
// pasted). Field order, widths and padding are interface facts of the binary
// format - every struct size is locked by a static_assert.
//
// Conventions:
// - All "index" fields are byte offsets. Offsets in studiohdr_t are relative
//   to the file start; offsets in any other struct are relative to that
//   struct's own first byte (including studiohdr2_t's).
// - Pointer-sized slots in the original headers (IMaterial*, cache pointers)
//   are declared as int32 pairs here; they are written zeroed on disk.
// - Struct member types use the pulse::math value types (plain float PODs).

#ifndef PULSEMDL_FORMAT_MDL_H
#define PULSEMDL_FORMAT_MDL_H

#include <cstdint>

#include "math/compressed.h" // float16 (zero-frame ik phases)
#include "math/math.h"

namespace pulse::format {

using math::Vector2;
using math::Vector3;
using math::Quaternion;
using math::matrix3x4;

// RadianEuler / QAngle are three floats on disk, same layout as Vector3.
using RadianEuler = math::Vector3;
using QAngle = math::Vector3;

// --- File ids ---------------------------------------------------------------

// "IDST" / "IDAG" little-endian.
inline constexpr int32_t kIdStudioHeader = ('T' << 24) + ('S' << 16) + ('D' << 8) + 'I';
inline constexpr int32_t kIdStudioAnimGroupHeader = ('G' << 24) + ('A' << 16) + ('D' << 8) + 'I';

// --- studiohdr flags (mdl build-time subset) ---------------------------------

inline constexpr int32_t STUDIOHDR_FLAGS_AUTOGENERATED_HITBOX = 1 << 0;
inline constexpr int32_t STUDIOHDR_FLAGS_FORCE_OPAQUE = 1 << 2;
inline constexpr int32_t STUDIOHDR_FLAGS_TRANSLUCENT_TWOPASS = 1 << 3;
inline constexpr int32_t STUDIOHDR_FLAGS_STATIC_PROP = 1 << 4;
inline constexpr int32_t STUDIOHDR_FLAGS_HASSHADOWLOD = 1 << 6;
inline constexpr int32_t STUDIOHDR_FLAGS_NO_FORCED_FADE = 1 << 11;
inline constexpr int32_t STUDIOHDR_FLAGS_FORCE_PHONEME_CROSSFADE = 1 << 12;
inline constexpr int32_t STUDIOHDR_FLAGS_CONSTANT_DIRECTIONAL_LIGHT_DOT = 1 << 13;
inline constexpr int32_t STUDIOHDR_FLAGS_AMBIENT_BOOST = 1 << 16;
inline constexpr int32_t STUDIOHDR_FLAGS_DO_NOT_CAST_SHADOWS = 1 << 17;
inline constexpr int32_t STUDIOHDR_FLAGS_CAST_TEXTURE_SHADOWS = 1 << 18;
inline constexpr int32_t STUDIOHDR_FLAGS_VERT_ANIM_FIXED_POINT_SCALE = 1 << 21;
inline constexpr int32_t STUDIOHDR_FLAGS_OVER_BUDGET = 1 << 23;
inline constexpr int32_t STUDIOHDR_FLAGS_EXTRA_VERTEX_DATA = 1 << 26;

// --- bone flags ---------------------------------------------------------------

inline constexpr int32_t BONE_PHYSICALLY_SIMULATED = 0x01;
inline constexpr int32_t BONE_PHYSICS_PROCEDURAL = 0x02;
inline constexpr int32_t BONE_ALWAYS_PROCEDURAL = 0x04;
inline constexpr int32_t BONE_USED_BY_HITBOX = 0x00000100;
inline constexpr int32_t BONE_USED_BY_ATTACHMENT = 0x00000200;
inline constexpr int32_t BONE_USED_BY_VERTEX_LOD0 = 0x00000400;
inline constexpr int32_t BONE_USED_BY_VERTEX_MASK = 0x0003FC00;
inline constexpr int32_t BONE_USED_BY_BONE_MERGE = 0x00040000;
inline constexpr int32_t BONE_ALWAYS_SETUP = 0x00080000;
inline constexpr int32_t BONE_USED_BY_ANYTHING = 0x000FFF00;
inline constexpr int32_t BONE_FIXED_ALIGNMENT = 0x00100000;
inline constexpr int32_t BONE_HAS_SAVEFRAME_POS = 0x00200000;   // Vector48
inline constexpr int32_t BONE_HAS_SAVEFRAME_ROT64 = 0x00400000; // Quaternion64
inline constexpr int32_t BONE_HAS_SAVEFRAME_ROT32 = 0x00800000; // Quaternion32

// bone (or model) contents. See BSP contents flags; solid is the default.
inline constexpr int32_t CONTENTS_SOLID = 0x1;
inline constexpr int32_t CONTENTS_GRATE = 0x8;
inline constexpr int32_t CONTENTS_MONSTER = 0x2000000;
inline constexpr int32_t CONTENTS_DEBRIS = 0x4000000;
inline constexpr int32_t CONTENTS_LADDER = 0x20000000;

// --- per-bone-per-anim RLE flags ---------------------------------------------

inline constexpr uint8_t STUDIO_ANIM_RAWPOS = 0x01;  // Vector48
inline constexpr uint8_t STUDIO_ANIM_RAWROT = 0x02;  // Quaternion48
inline constexpr uint8_t STUDIO_ANIM_ANIMPOS = 0x04; // mstudioanim_valueptr_t
inline constexpr uint8_t STUDIO_ANIM_ANIMROT = 0x08; // mstudioanim_valueptr_t
inline constexpr uint8_t STUDIO_ANIM_DELTA = 0x10;
inline constexpr uint8_t STUDIO_ANIM_RAWROT2 = 0x20; // Quaternion64

// --- per-bone frame-animation flags (STUDIO_FRAMEANIM sections) --------------
// One byte per bone, ahead of the constant block. "CONST" values live once in
// the constant block, "ANIM" values once per frame in the frame block.

inline constexpr uint8_t STUDIO_FRAME_CONST_POS = 0x01;  // Vector48 in constants
inline constexpr uint8_t STUDIO_FRAME_CONST_ROT = 0x02;  // Quaternion48 in constants
inline constexpr uint8_t STUDIO_FRAME_ANIM_POS = 0x04;   // Vector48 per frame
inline constexpr uint8_t STUDIO_FRAME_ANIM_ROT = 0x08;   // Quaternion48 per frame
inline constexpr uint8_t STUDIO_FRAME_ANIM_POS2 = 0x10;  // Vector3 per frame
inline constexpr uint8_t STUDIO_FRAME_CONST_POS2 = 0x20; // Vector3 in constants
inline constexpr uint8_t STUDIO_FRAME_CONST_ROT2 = 0x40; // Quaternion48S in constants
inline constexpr uint8_t STUDIO_FRAME_ANIM_ROT2 = 0x80;  // Quaternion48S per frame

// --- animation / sequence flags -----------------------------------------------

inline constexpr int32_t STUDIO_LOOPING = 0x0001;
inline constexpr int32_t STUDIO_SNAP = 0x0002;
inline constexpr int32_t STUDIO_DELTA = 0x0004;
inline constexpr int32_t STUDIO_AUTOPLAY = 0x0008;
inline constexpr int32_t STUDIO_POST = 0x0010;
inline constexpr int32_t STUDIO_ALLZEROS = 0x0020;
inline constexpr int32_t STUDIO_FRAMEANIM = 0x0040;
inline constexpr int32_t STUDIO_CYCLEPOSE = 0x0080;
inline constexpr int32_t STUDIO_REALTIME = 0x0100;
inline constexpr int32_t STUDIO_LOCAL = 0x0200;
inline constexpr int32_t STUDIO_HIDDEN = 0x0400;
inline constexpr int32_t STUDIO_OVERRIDE = 0x0800;
inline constexpr int32_t STUDIO_ACTIVITY = 0x1000;
inline constexpr int32_t STUDIO_EVENT = 0x2000;
inline constexpr int32_t STUDIO_WORLD = 0x4000;
inline constexpr int32_t STUDIO_NOFORCELOOP = 0x8000;
inline constexpr int32_t STUDIO_EVENT_CLIENT = 0x10000;
inline constexpr int32_t STUDIO_WORLD_AND_RELATIVE = 0x20000;
inline constexpr int32_t STUDIO_ROOTXFORM = 0x40000;

// motion type flags (movement / bone controllers)
inline constexpr int32_t STUDIO_X = 0x00000001;
inline constexpr int32_t STUDIO_Y = 0x00000002;
inline constexpr int32_t STUDIO_Z = 0x00000004;
inline constexpr int32_t STUDIO_XR = 0x00000008;
inline constexpr int32_t STUDIO_YR = 0x00000010;
inline constexpr int32_t STUDIO_ZR = 0x00000020;
inline constexpr int32_t STUDIO_LX = 0x00000040;
inline constexpr int32_t STUDIO_LY = 0x00000080;
inline constexpr int32_t STUDIO_LZ = 0x00000100;
inline constexpr int32_t STUDIO_LINEAR = 0x00001000;

// --- structs -------------------------------------------------------------------

struct mstudiobone_t {
    int32_t sznameindex;
    int32_t parent;
    int32_t bonecontroller[6]; // -1 == none
    // default (bind pose) values, local to parent
    Vector3 pos;
    Quaternion quat;
    RadianEuler rot;
    // compression scale
    Vector3 posscale;
    Vector3 rotscale;
    matrix3x4 poseToBone;
    Quaternion qAlignment;
    int32_t flags;
    int32_t proctype;
    int32_t procindex;
    int32_t physicsbone;
    int32_t surfacepropidx;
    int32_t contents;
    int32_t surfacepropLookup;
    int32_t unused[7];
};
static_assert(sizeof(mstudiobone_t) == 216, "mstudiobone_t layout");

// mstudiobone_t::proctype. Only QUATINTERP and JIGGLE are produced; the rest
// are listed so the value space is documented in one place.
inline constexpr int32_t STUDIO_PROC_AXISINTERP = 1;
inline constexpr int32_t STUDIO_PROC_QUATINTERP = 2;
inline constexpr int32_t STUDIO_PROC_AIMATBONE = 3;
inline constexpr int32_t STUDIO_PROC_AIMATATTACH = 4;
inline constexpr int32_t STUDIO_PROC_JIGGLE = 5;

// Procedural bone data for STUDIO_PROC_QUATINTERP, reached through
// mstudiobone_t::procindex (a byte offset relative to the owning bone).
//
// One trigger: when the control bone's orientation approaches `trigger`, the
// driven bone is blended toward `pos`/`quat`. inv_tolerance is the reciprocal
// of the trigger's angular influence in RADIANS, so a wider tolerance yields a
// smaller value.
struct mstudioquatinterpinfo_t {
    float inv_tolerance; // 1 / radian angle of trigger influence
    Quaternion trigger;  // control orientation to match
    Vector3 pos;         // driven bone position at full influence
    Quaternion quat;     // driven bone orientation at full influence
};
static_assert(sizeof(mstudioquatinterpinfo_t) == 48, "mstudioquatinterpinfo_t layout");

struct mstudioquatinterpbone_t {
    int32_t control; // bone index whose local transform is tested
    int32_t numtriggers;
    int32_t triggerindex; // byte offset to mstudioquatinterpinfo_t[], relative to this
};
static_assert(sizeof(mstudioquatinterpbone_t) == 12, "mstudioquatinterpbone_t layout");

// mstudiojigglebone_t::flags
inline constexpr int32_t JIGGLE_IS_FLEXIBLE = 0x01;
inline constexpr int32_t JIGGLE_IS_RIGID = 0x02;
inline constexpr int32_t JIGGLE_HAS_YAW_CONSTRAINT = 0x04;
inline constexpr int32_t JIGGLE_HAS_PITCH_CONSTRAINT = 0x08;
inline constexpr int32_t JIGGLE_HAS_ANGLE_CONSTRAINT = 0x10;
inline constexpr int32_t JIGGLE_HAS_LENGTH_CONSTRAINT = 0x20;
inline constexpr int32_t JIGGLE_HAS_BASE_SPRING = 0x40;
inline constexpr int32_t JIGGLE_IS_BOING = 0x80;

// Procedural bone data for STUDIO_PROC_JIGGLE, reached through
// mstudiobone_t::procindex (a byte offset relative to the owning bone).
// All angles are radians; boingImpactAngle is already a cosine.
struct mstudiojigglebone_t {
    int32_t flags;

    // general
    float length;  // distance from the bone base, along the bone, to the tip
    float tipMass;

    // flexible
    float yawStiffness;
    float yawDamping;
    float pitchStiffness;
    float pitchDamping;
    float alongStiffness;
    float alongDamping;

    // angle constraint
    float angleLimit; // max deflection of the tip

    // yaw constraint
    float minYaw;
    float maxYaw;
    float yawFriction;
    float yawBounce;

    // pitch constraint
    float minPitch;
    float maxPitch;
    float pitchFriction;
    float pitchBounce;

    // base spring
    float baseMass;
    float baseStiffness;
    float baseDamping;
    float baseMinLeft;
    float baseMaxLeft;
    float baseLeftFriction;
    float baseMinUp;
    float baseMaxUp;
    float baseUpFriction;
    float baseMinForward;
    float baseMaxForward;
    float baseForwardFriction;

    // boing
    float boingImpactSpeed;
    float boingImpactAngle;
    float boingDampingRate;
    float boingFrequency;
    float boingAmplitude;
};
static_assert(sizeof(mstudiojigglebone_t) == 140, "mstudiojigglebone_t layout");

// Procedural bone data for STUDIO_PROC_AIMATBONE / STUDIO_PROC_AIMATATTACH,
// reached through mstudiobone_t::procindex. `aim` is a bone index for the
// former and an attachment index for the latter - the proctype picks which.
struct mstudioaimatbone_t {
    int32_t parent;
    int32_t aim;
    Vector3 aimvector;
    Vector3 upvector;
    Vector3 basepos;
};
static_assert(sizeof(mstudioaimatbone_t) == 44, "mstudioaimatbone_t layout");

// SoA copy of the bone table (written only when numbones > 1); all *index
// offsets relative to this struct.
struct mstudiolinearbone_t {
    int32_t numbones;
    int32_t flagsindex;
    int32_t parentindex;
    int32_t posindex;
    int32_t quatindex;
    int32_t rotindex;
    int32_t posetoboneindex;
    int32_t posscaleindex;
    int32_t rotscaleindex;
    int32_t qalignmentindex;
    int32_t unused[6];
};
static_assert(sizeof(mstudiolinearbone_t) == 64, "mstudiolinearbone_t layout");

struct mstudiobonecontroller_t {
    int32_t bone;
    int32_t type;
    float start;
    float end;
    int32_t rest;
    int32_t inputfield;
    int32_t unused[8];
};
static_assert(sizeof(mstudiobonecontroller_t) == 56, "mstudiobonecontroller_t layout");

struct mstudiobbox_t {
    int32_t bone;
    int32_t group;
    Vector3 bbmin;
    Vector3 bbmax;
    int32_t szhitboxnameindex; // 0 = unnamed
    QAngle angOffsetOrientation;
    float flCapsuleRadius;
    int32_t unused[4];
};
static_assert(sizeof(mstudiobbox_t) == 68, "mstudiobbox_t layout");

struct mstudiohitboxset_t {
    int32_t sznameindex;
    int32_t numhitboxes;
    int32_t hitboxindex;
};
static_assert(sizeof(mstudiohitboxset_t) == 12, "mstudiohitboxset_t layout");

struct mstudioattachment_t {
    int32_t sznameindex;
    uint32_t flags;
    int32_t localbone;
    matrix3x4 local;
    int32_t unused[8];
};
static_assert(sizeof(mstudioattachment_t) == 92, "mstudioattachment_t layout");

// --- animation data -------------------------------------------------------------

union mstudioanimvalue_t {
    struct {
        uint8_t valid;
        uint8_t total;
    } num;
    int16_t value;
};
static_assert(sizeof(mstudioanimvalue_t) == 2, "mstudioanimvalue_t layout");

// offsets relative to this struct; 0 = no data for that axis
struct mstudioanim_valueptr_t {
    int16_t offset[3];
};
static_assert(sizeof(mstudioanim_valueptr_t) == 6, "mstudioanim_valueptr_t layout");

// 4-byte header; payload (raw values or valueptrs, rot first) follows.
// nextoffset is relative to this struct, 0 for the last bone.
struct mstudio_rle_anim_t {
    uint8_t bone;
    uint8_t flags;
    int16_t nextoffset;
};
static_assert(sizeof(mstudio_rle_anim_t) == 4, "mstudio_rle_anim_t layout");

struct mstudiomovement_t {
    int32_t endframe;
    int32_t motionflags;
    float v0;
    float v1;
    float angle;
    Vector3 vector;
    Vector3 position;
};
static_assert(sizeof(mstudiomovement_t) == 44, "mstudiomovement_t layout");

struct mstudioanimsections_t {
    int32_t animblock;
    int32_t animindex;
};
static_assert(sizeof(mstudioanimsections_t) == 8, "mstudioanimsections_t layout");

// one demand-loadable chunk of the external .ani file; both offsets are from
// the start of that file. Entry 0 is the pseudo-block meaning "local to the
// .mdl" and stays zeroed.
struct mstudioanimblock_t {
    int32_t datastart;
    int32_t dataend;
};
static_assert(sizeof(mstudioanimblock_t) == 8, "mstudioanimblock_t layout");

// header of one STUDIO_FRAMEANIM section: a per-bone flag byte array follows
// immediately, then the constant block, then framelength bytes per frame.
struct mstudio_frame_anim_t {
    int32_t constantsoffset;
    int32_t frameoffset;
    int32_t framelength;
    int32_t unused[3];
};
static_assert(sizeof(mstudio_frame_anim_t) == 24, "mstudio_frame_anim_t layout");

struct mstudioanimdesc_t {
    int32_t baseptr; // negative offset back to studiohdr_t
    int32_t sznameindex;
    float fps;
    int32_t flags;
    int32_t numframes;
    int32_t nummovements;
    int32_t movementindex;
    int32_t ikrulezeroframeindex;
    int32_t unused1[5];
    int32_t animblock;
    int32_t animindex; // non-zero when anim data isn't in sections
    int32_t numikrules;
    int32_t ikruleindex;
    int32_t animblockikruleindex;
    int32_t numlocalhierarchy;
    int32_t localhierarchyindex;
    int32_t sectionindex;
    int32_t sectionframes; // frames per section, 0 if unsectioned
    int16_t zeroframespan;
    int16_t zeroframecount;
    int32_t zeroframeindex;
    float zeroframestalltime;
};
static_assert(sizeof(mstudioanimdesc_t) == 100, "mstudioanimdesc_t layout");

struct mstudioautolayer_t {
    int16_t iSequence;
    int16_t iPose;
    int32_t flags;
    float start;
    float peak;
    float tail;
    float end;
};
static_assert(sizeof(mstudioautolayer_t) == 24, "mstudioautolayer_t layout");

struct mstudioiklock_t {
    int32_t chain;
    float flPosWeight;
    float flLocalQWeight;
    int32_t flags;
    int32_t unused[4];
};
static_assert(sizeof(mstudioiklock_t) == 32, "mstudioiklock_t layout");

// autolayer flags (mstudioautolayer_t.flags)
inline constexpr int32_t STUDIO_AL_POST = 0x0010;
inline constexpr int32_t STUDIO_AL_SPLINE = 0x0040;  // convert layer ramp in/out curve is a spline instead of linear
inline constexpr int32_t STUDIO_AL_XFADE = 0x0080;   // pre-bias the ramp curve to compense for a non-1 weight
inline constexpr int32_t STUDIO_AL_NOBLEND = 0x0200; // animation always blends at 1.0 (ignores weight)
inline constexpr int32_t STUDIO_AL_LOCAL = 0x1000;   // layer is a local context sequence
inline constexpr int32_t STUDIO_AL_POSE = 0x4000;    // layer blends using a pose parameter instead of parent cycle

// mstudioevent_t.type: set when the event is named rather than a numeric id
inline constexpr int32_t NEW_EVENT_STYLE = 1 << 10;

// ik rule types
inline constexpr int32_t IK_SELF = 1;
inline constexpr int32_t IK_WORLD = 2;
inline constexpr int32_t IK_GROUND = 3;
inline constexpr int32_t IK_RELEASE = 4;
inline constexpr int32_t IK_ATTACHMENT = 5;
inline constexpr int32_t IK_UNLATCH = 6;

struct mstudioposeparamdesc_t {
    int32_t sznameindex;
    int32_t flags;
    float start; // starting value
    float end;   // ending value
    float loop;  // looping range, 0 for no looping, 360 for rotations
};
static_assert(sizeof(mstudioposeparamdesc_t) == 20, "mstudioposeparamdesc_t layout");

struct mstudioiklink_t {
    int32_t bone;
    Vector3 kneeDir; // ideal bending direction (per link, if applicable)
    Vector3 unused0;
};
static_assert(sizeof(mstudioiklink_t) == 28, "mstudioiklink_t layout");

struct mstudioikchain_t {
    int32_t sznameindex;
    int32_t linktype; // never assigned by the compiler -> 0
    int32_t numlinks;
    int32_t linkindex; // offset to mstudioiklink_t array, relative to this struct
};
static_assert(sizeof(mstudioikchain_t) == 16, "mstudioikchain_t layout");

struct mstudiocompressedikerror_t {
    float scale[6];
    int16_t offset[6]; // offsets to mstudioanimvalue_t streams, relative to this struct; 0 = none
};
static_assert(sizeof(mstudiocompressedikerror_t) == 36, "mstudiocompressedikerror_t layout");

struct mstudioikrule_t {
    int32_t index;
    int32_t type;
    int32_t chain;
    int32_t bone;
    int32_t slot; // iktarget slot, usually same as chain
    float height;
    float radius;
    float floor;
    Vector3 pos;
    Quaternion q;
    int32_t compressedikerrorindex; // relative to this rule
    int32_t unused2;
    int32_t iStart;       // raw integer start frame
    int32_t ikerrorindex; // uncompressed error path - never written
    float start;          // beginning of influence (normalized 0..1 phase)
    float peak;           // start of full influence
    float tail;           // end of full influence
    float end;            // end of all influence
    float unused3;
    float contact; // frame footstep makes ground contact (normalized)
    float drop;    // never written
    float top;     // never written
    int32_t unused6;
    int32_t unused7;
    int32_t unused8;
    int32_t szattachmentindex; // RAW string after the error streams, NOT string table
    int32_t unused[7];
};
static_assert(sizeof(mstudioikrule_t) == 152, "mstudioikrule_t layout");

struct mstudioikrulezeroframe_t {
    int16_t chain;
    int16_t slot;
    math::float16 start; // normalized phases, float16
    math::float16 peak;
    math::float16 tail;
    math::float16 end;
};
static_assert(sizeof(mstudioikrulezeroframe_t) == 12, "mstudioikrulezeroframe_t layout");

struct mstudioevent_t {
    float cycle;
    int32_t event;
    int32_t type;
    char options[64];
    int32_t szeventindex;
};
static_assert(sizeof(mstudioevent_t) == 80, "mstudioevent_t layout");

struct mstudioanimtag_t {
    int32_t tag; // runtime-resolved; 0 on disk like the reference's calloc
    float cycle;
    int32_t sztagindex;
};
static_assert(sizeof(mstudioanimtag_t) == 12, "mstudioanimtag_t layout");

struct mstudioactivitymodifier_t {
    int32_t sznameindex;
};
static_assert(sizeof(mstudioactivitymodifier_t) == 4, "mstudioactivitymodifier_t layout");

struct mstudioseqdesc_t {
    int32_t baseptr; // negative offset back to studiohdr_t
    int32_t szlabelindex;
    int32_t szactivitynameindex;
    int32_t flags;
    int32_t activity; // -1 until runtime indexing
    int32_t actweight;
    int32_t numevents;
    int32_t eventindex;
    Vector3 bbmin;
    Vector3 bbmax;
    int32_t numblends;
    int32_t animindexindex; // offset to groupsize[0]*groupsize[1] shorts
    int32_t movementindex;
    int32_t groupsize[2];
    int32_t paramindex[2];
    float paramstart[2];
    float paramend[2];
    int32_t paramparent;
    float fadeintime;  // 0.2 default
    float fadeouttime; // 0.2 default
    int32_t localentrynode;
    int32_t localexitnode;
    int32_t nodeflags;
    float entryphase;
    float exitphase;
    float lastframe;
    int32_t nextseq;
    int32_t pose;
    int32_t numikrules;
    int32_t numautolayers;
    int32_t autolayerindex;
    int32_t weightlistindex; // numbones floats, always present
    int32_t posekeyindex;
    int32_t numiklocks;
    int32_t iklockindex;
    int32_t keyvalueindex;
    int32_t keyvaluesize;
    int32_t cycleposeindex;
    int32_t activitymodifierindex;
    int32_t numactivitymodifiers;
    int32_t animtagindex;
    int32_t numanimtags;
    int32_t rootDriverIndex;
    int32_t unused[2];
};
static_assert(sizeof(mstudioseqdesc_t) == 212, "mstudioseqdesc_t layout");

// --- flex / morph ----------------------------------------------------------------

// flex rule opcodes (mstudioflexop_t::op)
inline constexpr int32_t STUDIO_CONST = 1;  // push float
inline constexpr int32_t STUDIO_FETCH1 = 2; // push flex controller value
inline constexpr int32_t STUDIO_FETCH2 = 3; // push flex weight (%flexdesc)
inline constexpr int32_t STUDIO_ADD = 4;
inline constexpr int32_t STUDIO_SUB = 5;
inline constexpr int32_t STUDIO_MUL = 6;
inline constexpr int32_t STUDIO_DIV = 7;
inline constexpr int32_t STUDIO_NEG = 8; // not implemented at runtime
inline constexpr int32_t STUDIO_EXP = 9; // not implemented at runtime
inline constexpr int32_t STUDIO_OPEN = 10;  // parse-time only
inline constexpr int32_t STUDIO_CLOSE = 11; // parse-time only
inline constexpr int32_t STUDIO_COMMA = 12; // parse-time only
inline constexpr int32_t STUDIO_MAX = 13;
inline constexpr int32_t STUDIO_MIN = 14;
inline constexpr int32_t STUDIO_2WAY_0 = 15; // 2-way slider: RemapVal(-1, 0, 0, 1)
inline constexpr int32_t STUDIO_2WAY_1 = 16; // 2-way slider: RemapVal(0, 1, 0, 1)
inline constexpr int32_t STUDIO_NWAY = 17;   // n-way slider envelope
inline constexpr int32_t STUDIO_COMBO = 18;  // multiply last N stack values
inline constexpr int32_t STUDIO_DOMINATE = 19; // dominator suppression
inline constexpr int32_t STUDIO_DME_LOWER_EYELID = 20;
inline constexpr int32_t STUDIO_DME_UPPER_EYELID = 21;

// mstudioflexcontrollerui_t::remaptype
inline constexpr uint8_t FLEXCONTROLLER_REMAP_PASSTHRU = 0;
inline constexpr uint8_t FLEXCONTROLLER_REMAP_2WAY = 1;
inline constexpr uint8_t FLEXCONTROLLER_REMAP_NWAY = 2;
inline constexpr uint8_t FLEXCONTROLLER_REMAP_EYELID = 3;

// mstudioflex_t::vertanimtype
inline constexpr uint8_t STUDIO_VERT_ANIM_NORMAL = 0;
inline constexpr uint8_t STUDIO_VERT_ANIM_WRINKLE = 1;

struct mstudioflexdesc_t {
    int32_t szFACSindex;
};
static_assert(sizeof(mstudioflexdesc_t) == 4, "mstudioflexdesc_t layout");

struct mstudioflexcontroller_t {
    int32_t sztypeindex; // flex group name ("default")
    int32_t sznameindex;
    int32_t localToGlobal; // written -1, remapped at load time
    float min;
    float max;
};
static_assert(sizeof(mstudioflexcontroller_t) == 20, "mstudioflexcontroller_t layout");

struct mstudioflexcontrollerui_t {
    int32_t sznameindex;
    // union-like use: SIMPLE {control,-,-}, STEREO {left,right,-},
    // NWAY {control,-,value}, NWAY STEREO {left,right,value}. Byte offsets
    // to mstudioflexcontroller_t entries, relative to this struct.
    int32_t szindex0;
    int32_t szindex1;
    int32_t szindex2;
    uint8_t remaptype; // FLEXCONTROLLER_REMAP_*
    uint8_t stereo;    // bool
    uint8_t unused[2];
};
static_assert(sizeof(mstudioflexcontrollerui_t) == 20, "mstudioflexcontrollerui_t layout");

// vertex morph delta (pos/normal as float16; index is mesh-local)
struct mstudiovertanim_t {
    uint16_t index;
    uint8_t speed; // 255 * clamped speed
    uint8_t side;  // 255 * side (stereo balance)
    math::float16 delta[3];
    math::float16 ndelta[3];
};
static_assert(sizeof(mstudiovertanim_t) == 16, "mstudiovertanim_t layout");

struct mstudiovertanim_wrinkle_t {
    uint16_t index;
    uint8_t speed;
    uint8_t side;
    math::float16 delta[3];
    math::float16 ndelta[3];
    int16_t wrinkledelta; // fixed point: wrinkle / flVertAnimFixedPointScale, clamped +-32767
};
static_assert(sizeof(mstudiovertanim_wrinkle_t) == 18, "mstudiovertanim_wrinkle_t layout");

struct mstudioflex_t {
    int32_t flexdesc;
    float target0; // zero
    float target1; // one
    float target2; // one
    float target3; // zero
    int32_t numverts;
    int32_t vertindex; // byte offset to the vertanim array
    int32_t flexpair;  // second flexdesc (stereo), 0 otherwise
    uint8_t vertanimtype; // STUDIO_VERT_ANIM_*
    uint8_t unusedchar[3];
    int32_t unused[6];
};
static_assert(sizeof(mstudioflex_t) == 60, "mstudioflex_t layout");

struct mstudioflexop_t {
    int32_t op;
    union {
        int32_t index;
        float value;
    } d;
};
static_assert(sizeof(mstudioflexop_t) == 8, "mstudioflexop_t layout");

struct mstudioflexrule_t {
    int32_t flex; // flexdesc driven by this rule
    int32_t numops;
    int32_t opindex;
};
static_assert(sizeof(mstudioflexrule_t) == 12, "mstudioflexrule_t layout");

// --- bone flex drivers ----------------------------------------------------------

// StudioBoneFlexComponent_t - the bone component that drives a flex controller.
// Only the three translation axes exist; rotation was never implemented.
inline constexpr int32_t STUDIO_BONE_FLEX_INVALID = -1;
inline constexpr int32_t STUDIO_BONE_FLEX_TX = 0;
inline constexpr int32_t STUDIO_BONE_FLEX_TY = 1;
inline constexpr int32_t STUDIO_BONE_FLEX_TZ = 2;

struct mstudioboneflexdrivercontrol_t {
    int32_t m_nBoneComponent;       // STUDIO_BONE_FLEX_*
    int32_t m_nFlexControllerIndex; // flex controller driven
    float m_flMin;                  // bone component value mapped to 0
    float m_flMax;                  // bone component value mapped to 1
};
static_assert(sizeof(mstudioboneflexdrivercontrol_t) == 16,
              "mstudioboneflexdrivercontrol_t layout");

struct mstudioboneflexdriver_t {
    int32_t m_nBoneIndex;
    int32_t m_nControlCount;
    int32_t m_nControlIndex; // relative to THIS struct
    int32_t unused[3];
};
static_assert(sizeof(mstudioboneflexdriver_t) == 24, "mstudioboneflexdriver_t layout");

// --- geometry -------------------------------------------------------------------

struct mstudiobodyparts_t {
    int32_t sznameindex;
    int32_t nummodels;
    int32_t base;
    int32_t modelindex;
};
static_assert(sizeof(mstudiobodyparts_t) == 16, "mstudiobodyparts_t layout");

// Trailing runtime-pointer area of mstudiomodel_t / mstudiomesh_t. On disk it
// is always zeroed; 32/64-bit builds carve it up differently but the total
// byte count is identical.
struct mstudio_modelvertexdata_t {
    int32_t pVertexData[2];
    int32_t pTangentData[2];
    int32_t pExtraData[2];
};
static_assert(sizeof(mstudio_modelvertexdata_t) == 24, "mstudio_modelvertexdata_t layout");

struct mstudio_meshvertexdata_t {
    int32_t unused_modelvertexdata;
    int32_t numLODVertexes[8]; // filled by the post-write fixup pass
    int32_t modelvertexdata[2]; // serialized pointer, zeroed on disk
};
static_assert(sizeof(mstudio_meshvertexdata_t) == 44, "mstudio_meshvertexdata_t layout");

struct mstudiomesh_t {
    int32_t material;
    int32_t modelindex; // negative offset back to owning mstudiomodel_t
    int32_t numvertices;
    int32_t vertexoffset; // into the model's vertex range
    int32_t numflexes;
    int32_t flexindex;
    int32_t materialtype;
    int32_t materialparam;
    int32_t meshid; // sequential ordinal across the file
    Vector3 center;
    mstudio_meshvertexdata_t vertexdata;
    int32_t unused[6];
};
static_assert(sizeof(mstudiomesh_t) == 116, "mstudiomesh_t layout");

struct mstudiomodel_t {
    char name[64]; // inline, NOT string table
    int32_t type;
    float boundingradius;
    int32_t nummeshes;
    int32_t meshindex;
    int32_t numvertices;
    int32_t vertexindex;   // BYTE offset into the .vvd vertex block
    int32_t tangentsindex; // BYTE offset into the .vvd tangent block
    int32_t numattachments;
    int32_t attachmentindex;
    int32_t numeyeballs;
    int32_t eyeballindex;
    mstudio_modelvertexdata_t vertexdata;
    int32_t unused[4];
};
static_assert(sizeof(mstudiomodel_t) == 148, "mstudiomodel_t layout");

// Eyeball. NOTE: `unused[4]` is documented in the SDK as "These were used
// before, so not guaranteed to be 0" - the reference leaves whatever the
// calloc'd s_eyeball_t carried, so treat it as a leaked-bytes site like the
// other runtime-pointer slots rather than assuming zero.
struct mstudioeyeball_t {
    int32_t sznameindex;
    int32_t bone;
    Vector3 org;
    float zoffset;
    float radius;
    Vector3 up;
    Vector3 forward;
    int32_t texture; // mesh material index

    int32_t unused1;
    float iris_scale;
    int32_t unused2;

    int32_t upperflexdesc[3]; // raiser, neutral, lowerer
    int32_t lowerflexdesc[3];
    float uppertarget[3]; // radians: raised, neutral, lowered
    float lowertarget[3];

    int32_t upperlidflexdesc;
    int32_t lowerlidflexdesc;
    int32_t unused[4];
    uint8_t m_bNonFACS; // unused before version 44
    char unused3[3];
    int32_t unused4[7];
};
static_assert(sizeof(mstudioeyeball_t) == 172, "mstudioeyeball_t layout");

struct mstudiomouth_t {
    int32_t bone;
    Vector3 forward;
    int32_t flexdesc;
};
static_assert(sizeof(mstudiomouth_t) == 20, "mstudiomouth_t layout");

struct mstudiotexture_t {
    int32_t sznameindex;
    int32_t flags;
    int32_t used;
    int32_t unused1;
    int32_t material_ptrs[2]; // IMaterial*/client ptr slots, zeroed on disk
    int32_t unused[10];
};
static_assert(sizeof(mstudiotexture_t) == 64, "mstudiotexture_t layout");

struct mstudiosrcbonetransform_t {
    int32_t sznameindex;
    matrix3x4 pretransform;
    matrix3x4 posttransform;
};
static_assert(sizeof(mstudiosrcbonetransform_t) == 100, "mstudiosrcbonetransform_t layout");

// $modelgrouppreset entry. iValue/iMask are mixed-radix over the bodypart
// bases, NOT bit flags - iMask holds 1*base for each part the preset sets.
struct mstudiobodygrouppreset_t {
    int32_t sznameindex;
    int32_t iValue;
    int32_t iMask;
};
static_assert(sizeof(mstudiobodygrouppreset_t) == 12, "mstudiobodygrouppreset_t layout");

// --- headers --------------------------------------------------------------------

// Written immediately after studiohdr_t, always. Offsets relative to THIS struct.
struct studiohdr2_t {
    int32_t numsrcbonetransform;
    int32_t srcbonetransformindex;
    int32_t illumpositionattachmentindex;
    float flMaxEyeDeflection; // 0 = default cos(30)
    int32_t linearboneindex;  // 0 when numbones <= 1
    int32_t sznameindex;      // full model name (string table)
    int32_t m_nBoneFlexDriverCount;
    int32_t m_nBoneFlexDriverIndex;
    int32_t m_nBodyGroupPresetCount;
    int32_t m_nBodyGroupPresetIndex;
    int32_t padding_unused;
    int32_t virtualModel[2];   // serialized pointers, zeroed on disk
    int32_t animblockModel[2];
    int32_t pVertexBase[2];
    int32_t pIndexBase[2];
    int32_t reserved[44];
};
static_assert(sizeof(studiohdr2_t) == 252, "studiohdr2_t layout");

// $includemodel entry. The reference only ever fills sznameindex; szlabelindex
// stays 0 (the block is calloc'd).
struct mstudiomodelgroup_t {
    int32_t szlabelindex;
    int32_t sznameindex;
};
static_assert(sizeof(mstudiomodelgroup_t) == 8, "mstudiomodelgroup_t layout");

struct studiohdr_t {
    int32_t id;      // kIdStudioHeader
    int32_t version; // 49
    int32_t checksum; // shared with .vvd/.vtx/.phy
    char name[64];
    int32_t length; // total file size
    Vector3 eyeposition;
    Vector3 illumposition;
    Vector3 hull_min;
    Vector3 hull_max;
    Vector3 view_bbmin;
    Vector3 view_bbmax;
    int32_t flags;
    int32_t numbones;
    int32_t boneindex;
    int32_t numbonecontrollers;
    int32_t bonecontrollerindex;
    int32_t numhitboxsets;
    int32_t hitboxsetindex;
    int32_t numlocalanim;
    int32_t localanimindex;
    int32_t numlocalseq;
    int32_t localseqindex;
    int32_t activitylistversion;
    int32_t eventsindexed;
    int32_t numtextures;
    int32_t textureindex;
    int32_t numcdtextures;
    int32_t cdtextureindex;
    int32_t numskinref;
    int32_t numskinfamilies;
    int32_t skinindex;
    int32_t numbodyparts;
    int32_t bodypartindex;
    int32_t numlocalattachments;
    int32_t localattachmentindex;
    int32_t numlocalnodes;
    int32_t localnodeindex;
    int32_t localnodenameindex;
    int32_t numflexdesc;
    int32_t flexdescindex;
    int32_t numflexcontrollers;
    int32_t flexcontrollerindex;
    int32_t numflexrules;
    int32_t flexruleindex;
    int32_t numikchains;
    int32_t ikchainindex;
    int32_t nummouths;
    int32_t mouthindex;
    int32_t numlocalposeparameters;
    int32_t localposeparamindex;
    int32_t surfacepropindex;
    int32_t keyvalueindex;
    int32_t keyvaluesize;
    int32_t numlocalikautoplaylocks;
    int32_t localikautoplaylockindex;
    float mass;       // 1.0 default
    int32_t contents; // CONTENTS_SOLID default
    int32_t numincludemodels;
    int32_t includemodelindex;
    int32_t unused_virtualModel;
    int32_t szanimblocknameindex;
    int32_t numanimblocks;
    int32_t animblockindex;
    int32_t unused_animblockModel;
    int32_t bonetablebynameindex;
    int32_t unused_pVertexBase;
    int32_t unused_pIndexBase;
    uint8_t constdirectionallightdot;
    uint8_t rootLOD;
    uint8_t numAllowedRootLODs;
    uint8_t unused[1];
    int32_t unused4;
    int32_t numflexcontrollerui;
    int32_t flexcontrolleruiindex;
    float flVertAnimFixedPointScale;
    int32_t surfacepropLookup;
    int32_t studiohdr2index;
    int32_t unused2[1];
};
static_assert(sizeof(studiohdr_t) == 408, "studiohdr_t layout");

} // namespace pulse::format

#endif // PULSEMDL_FORMAT_MDL_H
